CREATE TABLE categories (
    id         BIGSERIAL PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE transactions (
    -- UUIDv7 generated by the application: time-ordered, so inserts stay index-friendly.
    id              UUID PRIMARY KEY,
    booked_on       DATE           NOT NULL,
    -- Signed: negative = money out, positive = money in. NUMERIC is exact; never use float.
    amount          NUMERIC(19, 4) NOT NULL,
    -- ISO 4217 code, stored as the bank gave it. No conversion in the MVP.
    currency        VARCHAR(3)     NOT NULL,
    description     TEXT           NOT NULL,
    category_id     BIGINT REFERENCES categories (id),
    -- Who set the category. Lets rule re-runs skip MANUAL edits.
    category_source VARCHAR(10)    NOT NULL DEFAULT 'NONE',
    -- Rule that produced the category. FK to categorization_rules is added in the
    -- rule-engine migration; that table doesn't exist yet.
    matched_rule_id BIGINT,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),

    CONSTRAINT transactions_currency_format CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT transactions_category_source_valid CHECK (category_source IN ('NONE', 'RULE', 'MANUAL')),
    -- A rule can only be recorded when the source is RULE.
    CONSTRAINT transactions_rule_requires_rule_source
        CHECK (matched_rule_id IS NULL OR category_source = 'RULE'),
    -- A category source other than NONE needs a category.
    CONSTRAINT transactions_source_requires_category
        CHECK (category_source = 'NONE' OR category_id IS NOT NULL)
);

-- One index per access path of GET /transactions filters. Each one speeds reads and slows writes,
-- so only the filters in the Week 2 scope get an index.
CREATE INDEX idx_transactions_booked_on ON transactions (booked_on);
CREATE INDEX idx_transactions_category_booked_on ON transactions (category_id, booked_on);
CREATE INDEX idx_transactions_currency ON transactions (currency);
